name: utoolbox
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 视频播放
  media_kit: ^1.1.9
  media_kit_video: ^1.2.2
  media_kit_libs_video: ^1.0.4

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.1
  get: ^4.6.6 #状态管理、路由管理、国际化
  dio: ^5.3.3 #网络请求
  hive: ^2.2.3 #持久化存储
  hive_flutter: ^1.1.0 #持久化存储
  logger: ^2.0.2+1 #日志
  intl: ^0.18.1 #国际化
  lottie: ^2.6.0 #lottie动画
  package_info_plus: ^4.2.0 #包信息
  permission_handler: ^11.0.1 #权限处理
  share_plus: ^7.2.1 #分享
  wakelock_plus: ^1.1.3 #屏幕常亮
  device_info_plus: ^9.1.0
  url_launcher: ^6.1.14
  flutter_smart_dialog: ^4.9.4
  remixicon: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/
